apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coder-server
  template:
    metadata:
      labels:
        app: coder-server
    spec:
      containers:
        - name: coder-server
          image: rideparkcity/back-70210:1.0.0
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: coder-service
spec:
  selector:
    app: coder-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort